---
- name: Copy the Process Exporter systemd service file
  template:
    src: process_exporter.service.j2
    dest: /etc/systemd/system/process_exporter.service
    owner: root
    group: root
    mode: 0644
  notify: restart process_exporter

- name: Create the process_exporter folder
  file:
    path: "{{ process_exporter_config_directory }}"
    state: directory
    owner: root
    group: "{{ process_exporter_system_group }}"
    mode: 0755

- name: Copy the process_exporter config
  template:
    src: process_exporter.yml.j2
    dest: "{{ process_exporter_config_directory }}/process_exporter.yml"
    owner: "{{ process_exporter_system_user }}"
    group: "{{ process_exporter_system_group }}"
    mode: 0644

- name: Allow Process Exporter port in SELinux on RedHat OS family
  seport:
    ports: "{{ process_exporter_web_listen_address.split(':')[1] }}"
    proto: tcp
    setype: http_port_t
    state: present
  when:
    - ansible_version.full is version_compare('2.4', '>=')
    - ansible_selinux.status == "enabled"
