---
- name: Create the process_exporter group
  group:
    name: "{{ process_exporter_system_group }}"
    state: present
    system: true
  when: process_exporter_system_group != "root"

- name: Create the process_exporter user
  user:
    name: "{{ process_exporter_system_user }}"
    groups: "{{ process_exporter_system_group }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    createhome: false
    home: /
  when: process_exporter_system_user != "root"

- name: Download process_exporter binary to local folder
  become: false
  get_url:
    url: "https://github.com/ncabatoff/process-exporter/releases/download/v{{ process_exporter_version }}/process-exporter-{{ process_exporter_version }}.linux-{{ go_arch }}.tar.gz"
    dest: "/tmp/process-exporter-{{ process_exporter_version }}.linux-{{ go_arch }}.tar.gz"
  register: _download_binary
  until: _download_binary is succeeded
  retries: 5
  delay: 2
  delegate_to: localhost
  check_mode: false

- name: Unpack process_exporter binary
  become: false
  unarchive:
    src: "/tmp/process-exporter-{{ process_exporter_version }}.linux-{{ go_arch }}.tar.gz"
    dest: "/tmp"
    creates: "/tmp/process-exporter-{{ process_exporter_version }}.linux-{{ go_arch }}/process-exporter"
  delegate_to: localhost
  check_mode: false

- name: Propagate process_exporter binaries
  copy:
    src: "/tmp/process-exporter-{{ process_exporter_version }}.linux-{{ go_arch }}/process-exporter"
    dest: "/usr/local/bin/process_exporter"
    mode: 0750
    owner: "{{ process_exporter_system_user }}"
    group: "{{ process_exporter_system_group }}"
  notify: restart process_exporter

