---
- name: Gather variables for each operating system
  include_vars: "{{ item }}"
  with_first_found:
    - files: 
      - "{{ ansible_distribution_file_variety | lower }}.yml"
      - "{{ ansible_distribution | lower }}.yml"
      - "{{ ansible_os_family | lower }}.yml"
      skip: true
  tags:
    - process_exporter_install
    - process_exporter_configure
    - process_exporter_run

- import_tasks: preflight.yml
  tags:
    - process_exporter_install
    - process_exporter_configure
    - process_exporter_run

- import_tasks: install.yml
  become: true
  tags:
    - process_exporter_install

- import_tasks: configure.yml
  become: true
  tags:
    - process_exporter_configure

- name: Ensure Process Exporter is enabled on boot
  become: true
  systemd:
    daemon_reload: true
    name: process_exporter
    enabled: true
    state: started
  tags:
    - process_exporter_run
